### ISSUE TITLE
Авторизация и пользователь

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#1]
1. **Добавить в проект авторизацию на основе Auth0.**

Мануал. https://auth0.com/blog/angular-2- authentication/
Пример, который делал я. https://github.com/zaikin-andrew/angular2-test-project
Должна быть возможность войти через VK, Github.

2. **Добавить сервис для работы с авторизацией и пользователем.** Логин, логаут, гет пользователя, обновление инфо пользователя, добавление адреса, запрос адресов.

3. **Добавить модель пользователя.** TS класс user. Для начала методы: геттеры для имени, данных для страницы профиля и адресов.

4. **Добавить поддержку хранения в LocalStorage.** Не пользоваться вендорными либами, нативные localStorage отлично работает.  Логин под другим пользователем не должен стирать предыдущего.

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/24/16 - 11/24/16
Work session total: 0:00:05
Grand total: 0:00:05

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/25/16 - 11/25/16
Work session total: 3:21:27
Grand total: 3:21:32

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/26/16 - 11/26/16
Work session total: 0:56:32
Grand total: 4:18:04
