### ISSUE TITLE
Добавить фильтры

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#10]
Добавить область с фильтрами(всеми доступными для всех API) на страницы поиска и категории.
Улучшить сервис для работы с фильтрами.

**Comment by user-two-myteam** [comment]
Потребуется 5 -6 часов

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/09/16 - 12/09/16
Work session total: 0:30:03
Grand total: 0:30:03

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/10/16 - 12/10/16
Work session total: 0:52:53
Grand total: 1:22:56

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/12/16 - 12/12/16
Work session total: 1:06:51
Grand total: 2:29:47

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/16/16 - 12/16/16
Work session total: 3:17:46
Grand total: 5:47:33

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/17/16 - 12/17/16
Work session total: 1:02:47
Grand total: 6:50:20

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/18/16 - 12/18/16
Work session total: 1:36:09
Grand total: 8:26:29

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/19/16 - 12/19/16
Work session total: 1:49:37
Grand total: 10:16:06
