### ISSUE TITLE
Добавление адресов

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#11]
Добавить модальные окна из http://valor-software.com/ng2-bootstrap/#/ .
![pic](http://cdn4.wpbeginner.com/wp-content/uploads/2012/02/gravityformsaddress.gif)
Сверстать форму для адреса. Страны https://restcountries.eu/ 
Использовать реактивные формы. Без 2-way binding. Все поля обязательны и имеют типы.

Если форма валидна, возвращаеть её результат на страницу адресов и добавлять пользователю. Проверку на повтор не делать.

**Comment by user-one-myteam** [comment]
4 часа примерно

**Comment by zaikin-andrew** [comment]
Тут не только добавить модалки, там же и дропдауны заработать должны :)

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/01/16 - 12/01/16
Work session total: 0:13:55
Grand total: 0:13:55

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/02/16 - 12/02/16
Work session total: 1:35:03
Grand total: 1:48:58

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/03/16 - 12/03/16
Work session total: 4:00:30
Grand total: 5:49:28
