### ISSUE TITLE
Вынести карточку товара в shared

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#12]
- Вынести в общие компоненты карточку товара и использовать во всех списках(главная, категории, поиск)
- Добавить кнопку "В корзину" и функционал к ней.

**Comment by user-two-myteam** [comment]
Потребуется 3 - 4 часа

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/01/16 - 12/01/16
Work session total: 0:55:13
Grand total: 0:55:13
