### ISSUE TITLE
Валюта

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#13]
- Добавить валюту для товаров в карточке и на странице продукта
- Добавить выбор валюты пользователю в настройках профиля(красивый селект из 3).
- Добавить pipe для отображения правильной цены в карточке в зависимости от выбранной пользователем.
- По-умолчанию - доллар.

**Comment by user-one-myteam** [comment]
примерное время 3 часа

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/03/16 - 12/03/16
Work session total: 0:00:01
Grand total: 0:00:01

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/04/16 - 12/04/16
Work session total: 1:55:30
Grand total: 1:55:31
