### ISSUE TITLE
Профиль и адреса

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#14]
- Добавить возможность обновлять данные пользователя на странице профиля. имя, ник, email, телефон, решите что еще можно добавить безопасного
- список адресов на другой странице с возможностью удалить или добавить

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/27/16 - 11/27/16
Work session total: 2:27:46
Grand total: 2:27:46

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/27/16 - 11/28/16
Work session total: 1:59:08
Grand total: 4:26:54
