### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#15]
Тут оформляется заказ. Итоговая цена, промокоды, адрес доставки и платежная система. Адрес можно выбрать один из своих или добавить новый через модалку. При вроде промокода(ANGULAR2) сообщается, что скидка 25% применена и добавляются новые цены на продукты и общую стоимость. Метод оплаты просто надо выбрать из дропдауна(PayPal, CreditCard, Cash, WebMoney, QIWI, Bitcoin). Кнопка «Оплатить». Делаем задержку в 5 секунд на псевдообработку.

- Список товаров, общая цена. Ничего нельзя изменять. 
- Поле промокода и метод для нее.
- Выбор адреса, добавление нового
- Метод оплаты, просто радиобаттоны с названиями и картинками
- Формирование заказа и добавление к пользователю в профиль.

**Comment by user-one-myteam** [comment]
примерно 8 часов

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/06/16 - 12/06/16
Work session total: 3:23:06
Grand total: 3:23:06

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/07/16 - 12/07/16
Work session total: 0:56:57
Grand total: 4:20:03

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/10/16 - 12/10/16
Work session total: 0:00:01
Grand total: 4:20:04
