### ISSUE TITLE
Подтверждение

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#16]
После оплаты попадаем сюда, Пишем пользователю, что заказ оплачем и скоро будет сформирован и выслан на такой то адрес. Ожидаемый срок поставки +2 недели (написать даты)

**Comment by zaikin-andrew** [comment]
Что тут со сроками и кто будет делать?

**Comment by user-one-myteam** [comment]
Кто первый освободится!!

**Comment by user-one-myteam** [comment]
Примерно 2-3 часа

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/10/16 - 12/10/16
Work session total: 1:34:10
Grand total: 1:34:10
