### ISSUE TITLE
Тоасты

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#17]
- добавить тоасты
- добавить оповещения на: добавление товара в корзину, изменение данных, адресов

**Comment by zaikin-andrew** [comment]
Что тут со сроками и кто будет делать?

**Comment by user-one-myteam** [comment]
Кто первый освободится!!

**Comment by zaikin-andrew** [comment]
Думаю стоит выбрать одну из https://github.com/akserg/ng2-toasty https://github.com/PointInside/ng2-toastr
Посмотрите какая удобнее.

**Comment by user-one-myteam** [comment]
Я её и хотел использовать, просто не могу перейти к этой задаче не как))

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/18/16 - 12/18/16
Work session total: 1:58:56
Grand total: 1:58:56
