### ISSUE TITLE
Основная структура проекта

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#2]
Добавить:

1. Shared module, для всех повторно используемых компонентов и сервисов.

2. Компоненты для страницы категории, поиска, страницы продукта, корзины, чекаута, профиля пользователя, подтверждения. Простые шаблоны сгенерировать. Добавить роутинг на каждую.

3. Добавить общий хедер с Лого(myTeam-Media-Shop), ссылками на категории, серч бар и юзер область с дропдауном для профиля, адресов, логаута, логина. Сёрч бар при enter ведет на страницу серча и сразу делает запрос.

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/25/16 - 11/25/16
Work session total: 1:19:26
Grand total: 1:19:26
