### ISSUE TITLE
Главная страница

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#27]
- на ней должны располагаться 3 полосы: по 5 карточек в ряд и по 2 ряда в полосе, всего по 10 карточек на каждую категорию.
- Использовать резолверы для каждой категории(подумать, один или 3шт)

![image](https://cloud.githubusercontent.com/assets/7475399/20802416/05dd40ee-b7fd-11e6-8be5-fbdd85cefb62.png)
Схема

**Comment by user-one-myteam** [comment]
Это все картинки чисто будут?

**Comment by zaikin-andrew** [comment]
Нет, карточки обычные.

**Comment by user-one-myteam** [comment]
А что если вернуть массив сервисов? 
return [this._musicService.latest(),return this._movieService.recent()] и так далее?

**Comment by zaikin-andrew** [comment]
не уверен что так получится. надо доки глянуть. там он промис, observable или дату(инфу) ждет. не думаю что он предназначен для массива observable.

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/18/16 - 12/18/16
Work session total: 1:52:22
Grand total: 1:52:22
