### ISSUE TITLE
Fake data generator

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#29]
- Создать супер простой express.js сервер из 1 файла
- Добавить в package.json команду для запуска сервера через nodemon и дополнить ею npm start, чтоб помимо ng cli стартовал еще и сервер.
- http://marak.github.io/faker.js/index.html добавить эту либу и подключить её к серверу
- Создать 1 роут `/api/selling`, который будет отдавать рандомные данные по продажам
- Создать схему покупки для рандоматора. Использовать имеющиеся поля нашего пользователя(включая адреса). Должны присутствовать личные данные пользователя, адрес на который был сделан заказ, полные данные товаров(название, описание, количество, стоимость), общая стоимость и т.д. Точнее поля подправим позже.
- Настроить прокси в angular-cli на порт этого сервера.

**Comment by user-one-myteam** [comment]
6-8 часов

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/10/16 - 12/10/16
Work session total: 2:27:21
Grand total: 2:27:21

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/11/16 - 12/11/16
Work session total: 1:19:21
Grand total: 3:46:42
