### ISSUE TITLE
Табличное представление данных

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#30]
- https://www.ag-grid.com/best-angular-2-data-grid подключить эти таблицы
- использовать компонент из админки для получения визуализации данных
- использовать рандоматор для получения данных, а таблицу для их представления

**Comment by user-one-myteam** [comment]
6-8 часов

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/15/16 - 12/15/16
Work session total: 7:00:09
Grand total: 7:00:09

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/16/16 - 12/16/16
Work session total: 4:04:43
Grand total: 11:04:52

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/17/16 - 12/17/16
Work session total: 6:15:47
Grand total: 17:20:39
