### ISSUE TITLE
Добавление админки

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#31]
- добавить модуль admin
- добавить отдельный роутинг для него с 3 страницами: заказы, аналитика, пользователи
- создать сервис для добычи данных с рандоматора. Методы: получение данных продаж и пользователей.

**Comment by user-one-myteam** [comment]
4-6 часов

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/11/16 - 12/11/16
Work session total: 1:36:03
Grand total: 1:36:03

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/12/16 - 12/12/16
Work session total: 1:03:12
Grand total: 2:39:15
