### ISSUE TITLE
Графическое представление

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#32]
- подключить http://valor-software.com/ng2-charts/
- в компоненте аналитика нарисовать графики заказов: Line Chart, Bar Chart, Doughnut Chart. Использовать Dynamic Chart чтоб анимация была. 
- какие данные из продаж использовать для формирования графиков оставляю на вашу фантазию :)
- должна быть кнопка обновить, которая запрашивает новую порцию данных из рандоматора. 
- добавить возможность выбирать временной интервал. Т.е. по одной оси будет время, за которое мы просматриваем график. Придется дописать рандоматор чтоб он генерил разное количество данных, в зависимости от временного диапазона, а если он не задан вывать стандартную порцию из 20 элементов.

**Comment by user-one-myteam** [comment]
4-5 часов

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/11/16 - 12/11/16
Work session total: 0:00:01
Grand total: 0:00:01

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/13/16 - 12/13/16
Work session total: 3:23:58
Grand total: 3:23:59

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/14/16 - 12/14/16
Work session total: 1:47:17
Grand total: 5:11:16

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/15/16 - 12/15/16
Work session total: 1:15:37
Grand total: 6:26:53
