### ISSUE TITLE
Создать сервис для работы с фильмами

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#4]
Вам потребуется написать обёртку этого API. Работаем только с фильмами.
Все без авторизации в сервисе.
![image](https://cloud.githubusercontent.com/assets/7475399/20482543/37a146f4-affe-11e6-9ea6-70c0dcaa0b19.png)

Доки - https://www.themoviedb.org/documentation/api

Необходимые методы:

1. getItem(id) - https://developers.themoviedb.org/3/movies
2. search(query, filters) - https://developers.themoviedb.org/3/search/search-movies
3. latest() - https://developers.themoviedb.org/3/movies/get-latest-movie

К каждому должны быть опциональные параметры. Пользоваться https://angular.io/docs/ts/latest/api/http/index/URLSearchParams-class.html для request string. 

Тестировать можно просто добавив запрос в ngOnInit в главный компонент и потом смотреть ответ в консоли или дебаггером.

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/25/16 - 11/25/16
Work session total: 0:53:07
Grand total: 0:53:07

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/25/16 - 11/26/16
Work session total: 1:24:07
Grand total: 2:17:14
