### ISSUE TITLE
Срочные фиксы

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#46]
Список срочных фиксов:
- cursor: pointer на дропдауны
- лоадеры (просто гифки, а лучше spin иконки, не знаю есть такие в glyphicons) во всех местах где мы чего то ожидаем. например games раздел на главной или данные в таблицу когда подгружаются.
- кнопка в карточке товара "Cart" -> "Add to cart"
-  myTeam-Media-Shop -> Media-Shop
- паддинг в карточке увеличить до 10px
- карточки товаров прилипли друг к другу. проблема с версткой бутстрапной.
- паддинги не ровные ![pic](https://d1ro8r1rbfn3jf.cloudfront.net/ms_87403/9zNO3oUV7aqWRK2rWbavGLoNtmQPdR/MyteamShop%2B2016-12-18%2B23-47-57.jpg?Expires=1482180497&Signature=cPVV4WKukP4U2fXfo6YHarOsoE9EeVPzypcqSJDJ4OccDAMooVKuEaIHjyYZwckLfLiXxRF~s~ADCwi9K~O-q1KNdYJWBLDLNdTia1ZERUBKezIIOWiUGufJGLTFAlf39KNRxj6si~Lt~uqNqYLvAJwPcbFh0wxHT7LhN5DhEP9Bj36-kTHGfL4mzJkIY8ca9lk2LP9-vhhduCi2ATolYHKJVepYo94PTnna-SKkIfl0SRG4gDwIBDEBN3VtaLK-fhUMPwKugQscx2TCzvaY~3OuUZupjqct8JVCnaE1Ng1CKhFegtU3cayrRd8q7meiDimGC-olnko7H2mroxoLeQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)
- без юзера доступен дропдаун с профилем и адресами, хотя не должен
- в поиске нет лейблов к из какой категории товар http://getbootstrap.com/components/#available-variations
- не ровно ![pic1](https://d1ro8r1rbfn3jf.cloudfront.net/ms_87403/BowOy3KhDktdRdS9eetRCb8G1B937j/MyteamShop%2B2016-12-18%2B23-52-39.jpg?Expires=1482180782&Signature=dNnYtqcxbQEEPls2f8VuUy-zXliUCrm7etLWPKd8Qr6eNebN4S3EwEeKnHoXZPqVMzSilcFZMt3ELEpzlCkLVSGJEpgSQIIvcWM-y3z87R75qPXvGrQwVovjuitZCKt2pgdY4d8mTxAPwsfkju-q4oC4BkVMgg80yXIJO~NIvAtOcTxAn8Esq2R9YifkqZdPdOWliloHABj1hRdS1dVhzyfveyGYsKx45iEU5WQg7sQtIFf6tw8Mbof6F0hDPHyvEB7wHEDfftbjIkJM0ZVVBapsY6inthsjf1g5a9jB7XAVk~y-YEQJ5lVWX3LVbrX7s1uClHZUFqWZdBGXeSbNJQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA) 
- скругление ![pic2](https://d1ro8r1rbfn3jf.cloudfront.net/ms_87403/iVO3LeOoXdtf0OqF7oeQOQRpfLCKjM/MyteamShop%2B2016-12-18%2B23-53-49.jpg?Expires=1482180841&Signature=nUuh4iiiqx-Q8tSakE9CnJi8MyJUZ0h4Nv36QEtm1ZXPlqND-QoDONHrsbzohTW9xjV~z0fAzEMM6ydng6E14SuCTKRXFYvgEOeLiUIUqnyIO7XS-6AXSFjwXRZBvi81ZjR~~gG9YdZusM06GVjeM8cwW2p-JrOCkapcDiiuj3lQppLf4IVp5xlpp91lo-M6w~ucOG5FeLvyQs9eFlVyNBkMNAkfu0EYA5qAuHrauUzxmk2F8TvdwZw9Zct2q8ygxsKJZU1koFkhMjIpWwp6l3-w7YcPV9C-7FMqpXOT6Ohx7NpL0i9nWvKs881-6ZliFkcH1SLjxmUvvDrvxRlVbg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/18/16 - 12/18/16
Work session total: 0:41:15
Grand total: 0:41:15

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/18/16 - 12/19/16
Work session total: 0:52:09
Grand total: 1:33:24
