### ISSUE TITLE
Страница категории

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#6]
_После реализации сервисов заняться этим._

- В зависимости от роута, делать запрос за данными нужной категории. 
- Запрос должен быть сделать резолвом
- Расположить данные по странице аккуратно и максимально используя данные
- В зависимости от категории будут немного отличаться шаблон(шаблон один).
- Возможно понадобится функция, предварительно обрабатывающая данные для удобной отрисовки в шаблоне.

**Comment by zaikin-andrew** [comment]
Я постараюсь сделать набросок для улучшения понимания. 
Однако творческий подход приветствуется!

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/28/16 - 11/28/16
Work session total: 2:19:22
Grand total: 2:19:22

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/29/16 - 11/29/16
Work session total: 2:18:24
Grand total: 4:37:46
