### ISSUE TITLE
Страница продукта

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#7]
_После завершения API_

- Резолвер в роут
- Один компонент для всех продуктов
- Отрисовать все данные

**Comment by user-two-myteam** [comment]
Потребуется 3 - 4 часа

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/02/16 - 12/02/16
Work session total: 2:16:45
Grand total: 2:16:45

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/05/16 - 12/05/16
Work session total: 2:03:38
Grand total: 4:20:23
