### ISSUE TITLE
Странца корзины

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#8]
1. Сервис для взаимодействия с корзиной(добавление, удаление, хранение, возврат информации, оплата)
2. Простая страница со списком товаров в корзине которые можно удалять из неё. Форма, с количеством товара, ценой, общей стоимостью. 
3. Переход на оплату только после логина. Кнопка задизейблена, напоминающая надпись.

**Comment by user-one-myteam** [comment]
Примерное время 3-4 часа

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 11/30/16 - 11/30/16
Work session total: 2:24:30
Grand total: 2:24:30

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/01/16 - 12/01/16
Work session total: 1:17:05
Grand total: 3:41:35
