### ISSUE TITLE
Странца search

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/myteam-shop#9]
1. Сёрч должен делать запросы на все 3 ресурса и вытаскивать по 10 товаров. Без пагинации.
2. Задержка при изменении параметра запроса в 2 секунды(rxjs debounce), чтоб не срабатывал часто.
3. На странице только сёрч бар и список результатов.
4. В результатах категории должны быть смешаны. (см rxjs)
5. При клике на карточку переход на страницу продукта.

**Comment by user-two-myteam** [comment]
Потребуется 4 - 5 часов

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/07/16 - 12/07/16
Work session total: 1:49:21
Grand total: 4:25:16

**Comment by user-two-myteam** [comment]
via Hubstaff
User: User Two
Project: MediaShop - https://app.hubstaff.com/projects/166048
Date Range: 12/08/16 - 12/08/16
Work session total: 1:47:49
Grand total: 6:13:05
